const heroes = [
  { name: 'D.Va', role: 'Tank', origin: 'South Korea' },
  { name: 'Doomfist', role: 'Tank', origin: 'Nigeria' },
  { name: 'Junker Queen', role: 'Tank', origin: 'Australia' },
  { name: 'Mauga', role: 'Tank', origin: 'Samoa' },
  { name: 'Orisa', role: 'Tank', origin: 'Nigeria' },
  { name: 'Ramattra', role: 'Tank', origin: 'Nepal' },
  { name: 'Reinhardt', role: 'Tank', origin: 'Germany' },
  { name: 'Roadhog', role: 'Tank', origin: 'Australia' },
  { name: 'Sigma', role: 'Tank', origin: 'Netherlands' },
  { name: 'Winston', role: 'Tank', origin: 'Horizon Lunar Colony' },
  { name: 'Wrecking Ball', role: 'Tank', origin: 'Horizon Lunar Colony' },
  { name: 'Zarya', role: 'Tank', origin: 'Russia' },
  { name: 'Ashe', role: 'Damage', origin: 'United States' },
  { name: 'Bastion', role: 'Damage', origin: 'Germany' },
  { name: 'Cassidy', role: 'Damage', origin: 'United States' },
  { name: 'Echo', role: 'Damage', origin: 'Singapore' },
  { name: 'Genji', role: 'Damage', origin: 'Japan' },
  { name: 'Hanzo', role: 'Damage', origin: 'Japan' },
  { name: 'Junkrat', role: 'Damage', origin: 'Australia' },
  { name: 'Mei', role: 'Damage', origin: 'China' },
  { name: 'Pharah', role: 'Damage', origin: 'Egypt' },
  { name: 'Reaper', role: 'Damage', origin: 'United States' },
  { name: 'Sojourn', role: 'Damage', origin: 'Canada' },
  { name: 'Soldier: 76', role: 'Damage', origin: 'United States' },
  { name: 'Sombra', role: 'Damage', origin: 'Mexico' },
  { name: 'Symmetra', role: 'Damage', origin: 'India' },
  { name: 'Torbjörn', role: 'Damage', origin: 'Sweden' },
  { name: 'Tracer', role: 'Damage', origin: 'United Kingdom' },
  { name: 'Venture', role: 'Damage', origin: 'Canada' },
  { name: 'Widowmaker', role: 'Damage', origin: 'France' },
  { name: 'Ana', role: 'Support', origin: 'Egypt' },
  { name: 'Baptiste', role: 'Support', origin: 'Haiti' },
  { name: 'Brigitte', role: 'Support', origin: 'Sweden' },
  { name: 'Illari', role: 'Support', origin: 'Peru' },
  { name: 'Juno', role: 'Support', origin: 'Mars Colony' },
  { name: 'Kiriko', role: 'Support', origin: 'Japan' },
  { name: 'Lifeweaver', role: 'Support', origin: 'Thailand' },
  { name: 'Lúcio', role: 'Support', origin: 'Brazil' },
  { name: 'Mercy', role: 'Support', origin: 'Switzerland' },
  { name: 'Moira', role: 'Support', origin: 'Ireland' },
  { name: 'Zenyatta', role: 'Support', origin: 'Nepal' }
];

const heroLore = {
  'D.Va': 'Hana Song is a former pro gamer who now pilots a state-of-the-art mech to defend South Korea from omnic threats emerging from the sea.',
  Doomfist: 'Akande Ogundimu believes conflict is the catalyst for human evolution, and he seeks to forge a stronger future through force as a Talon leader.',
  'Junker Queen': 'Odessa Stone seized control of Junkertown through brutal arena combat and now rules the irradiated outback with charisma and steel.',
  Mauga: 'A heavy assault specialist from Samoa, Mauga thrives on chaos and destruction while carrying out Talon operations with an intimidating grin.',
  Orisa: 'Built by Efi Oladele from the remains of OR15 defense bots, Orisa protects Numbani with adaptive intelligence and a steadfast sense of duty.',
  Ramattra: 'Once a monk advocating peace, Ramattra embraced revolution and formed Null Sector after seeing omnics denied justice and equal rights.',
  Reinhardt: 'A crusader of honor from Germany, Reinhardt Wilhelm fights with a rocket hammer and unbreakable spirit to protect those who cannot protect themselves.',
  Roadhog: 'Mako Rutledge became the ruthless enforcer Roadhog after Australia\'s omnium catastrophe, roaming as a masked outlaw from Junkertown.',
  Sigma: 'Brilliant astrophysicist Siebren de Kuiper was transformed by a gravity experiment gone wrong, leaving Talon to weaponize his fractured genius.',
  Winston: 'A super-intelligent gorilla from Horizon Lunar Colony, Winston became a scientist and hero inspired by Overwatch\'s ideals of hope.',
  'Wrecking Ball': 'Hammond, a genetically engineered hamster from the lunar colony, built a mechanized ball and fought his way to freedom in Junkertown.',
  Zarya: 'Aleksandra Zaryanova is a celebrated Russian soldier who turned her strength toward defending her homeland from omnic invasion.',
  Ashe: 'Elizabeth Caledonia Ashe leads the Deadlock Gang with sharp aim and sharper ambition, enforcing her own outlaw code in the American Southwest.',
  Bastion: 'An E54 Bastion unit once built for war, this curious omnic now wanders nature with its bird companion Ganymede, searching for purpose.',
  Cassidy: 'Cole Cassidy, a former Deadlock gunslinger, now travels the world trying to right wrongs with a revolver and hard-earned resolve.',
  Echo: 'Created by Dr. Mina Liao, Echo is an advanced adaptive robot designed to learn and evolve while carrying forward Overwatch\'s hopeful mission.',
  Genji: 'After near-fatal betrayal, Genji Shimada was rebuilt with cybernetics and later found peace through Zenyatta\'s teachings.',
  Hanzo: 'Heir to the Shimada empire, Hanzo abandoned his clan after a tragic duel and now seeks redemption for his past.',
  Junkrat: 'Jamison Fawkes is an explosives-obsessed anarchist from the Australian outback who turned accidental treasure into global chaos.',
  Mei: 'Dr. Mei-Ling Zhou is a climatologist who survived cryostasis in Antarctica and now fights to protect the world\'s future.',
  Pharah: 'Fareeha Amari serves as a decorated security captain in Raptora armor, striving to honor both her duty and her family legacy.',
  Reaper: 'Gabriel Reyes, once Overwatch\'s strike commander, became the shadowy mercenary Reaper after being twisted by deathly experiments.',
  Sojourn: 'Vivian Chase, known as Sojourn, is a disciplined former Overwatch captain whose cybernetic enhancements support precise tactical leadership.',
  'Soldier: 76': 'The vigilante Soldier: 76 is Jack Morrison, former Overwatch commander, uncovering conspiracies while waging a personal war for justice.',
  Sombra: 'Olivia Colomar is a brilliant hacker and infiltrator who manipulates global powers from the shadows with wit, stealth, and information control.',
  Symmetra: 'Satya Vaswani bends hard light into order and architecture, balancing Vishkar ideals with her growing sense of personal truth.',
  'Torbjörn': 'Master engineer Torbjörn Lindholm forged many of Overwatch\'s greatest weapons and now works to keep technology in responsible hands.',
  Tracer: 'Lena Oxton, the time-jumping Tracer, channels unstoppable optimism and chronal agility as one of Overwatch\'s most iconic agents.',
  Venture: 'Archaeologist Sloan Cameron, known as Venture, uses high-tech excavation gear to uncover ancient mysteries and protect cultural treasures.',
  Widowmaker: 'Once Amélie Lacroix, Widowmaker was transformed by Talon into a cold-hearted sniper whose emotions were almost entirely erased.',
  Ana: 'Ana Amari, founding Overwatch sniper and mother of Pharah, returned from presumed death to defend the world with unmatched precision.',
  Baptiste: 'Jean-Baptiste Augustin escaped Talon and now uses his combat medic training to save lives and fight for a better future.',
  Brigitte: 'Brigitte Lindholm, engineer and squire to Reinhardt, combines shielded frontline courage with mechanical ingenuity to protect allies.',
  Illari: 'Empowered by the Inti Warrior process, Illari carries solar energy abilities while bearing the burden of a tragic catastrophe.',
  Juno: 'Raised on Mars, Juno arrives on Earth with celestial curiosity and cutting-edge support tech to help safeguard humanity.',
  Kiriko: 'Kiriko Kamori blends fox-spirit magic, kunai precision, and street-level heroism to protect Kanezaka and its people.',
  Lifeweaver: 'Niran Pruksamanee, known as Lifeweaver, wields biolight technology to heal and defend while pursuing a compassionate vision for science.',
  'Lúcio': 'Brazilian DJ and activist Lúcio Correia dos Santos inspires resistance and unity through music-powered sonic technology.',
  Mercy: 'Dr. Angela Ziegler, Mercy, is a world-renowned healer whose Caduceus technology keeps teammates alive in the heat of battle.',
  Moira: 'Geneticist Moira O\'Deorain pushes scientific boundaries without ethical limits, harnessing biotic power for both healing and harm.',
  Zenyatta: 'A wandering omnic monk, Zenyatta teaches spiritual harmony while aiding those in need with floating orbs of healing and discord.'
};

const heroRates = {
  Ana: { winRate: '50.5%', pickRate: '6%' },
  Ashe: { winRate: '48.5%', pickRate: '5.6%' },
  Baptiste: { winRate: '50%', pickRate: '2.4%' },
  Bastion: { winRate: '50.4%', pickRate: '2.9%' },
  Brigitte: { winRate: '52.2%', pickRate: '2.2%' },
  Cassidy: { winRate: '49.2%', pickRate: '10.7%' },
  'D.Va': { winRate: '47.9%', pickRate: '7%' },
  Doomfist: { winRate: '50.8%', pickRate: '3.9%' }
};

window.OVERWATCH_DATA = { heroes, heroLore, heroRates };
